name: moneytracker
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  image_picker: ^1.2.0
  permission_handler: ^12.0.1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  fl_chart: ^1.1.1
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  hive_ce_generator: ^1.11.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf

flutter_native_splash:

  color: "#B2FF59"

  image: assets/images/logo.png

  android_12:

    color: "#B2FF59"

    image: assets/images/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.jpg"
  adaptive_icon_background: "#4CAF50"

  